/* ============================================= 
    Create Project Table-Spaces define datafile
   ============================================= */
--   
-- # DBA_MAIN_TS, assign to tablespace
CREATE TABLESPACE "DBA_MAIN_TS" DATAFILE '/db/knpc/domain/DBA_MAIN.DB' 
    SIZE 10485760 AUTOEXTEND ON NEXT 1048576 
    MAXSIZE 1048576000 LOGGING ONLINE PERMANENT BLOCKSIZE 8192 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE 
    DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/db/knpc/domain/DBA_MAIN.DB' RESIZE 10485760;
--
-- # INDEX_MAIN_TS
CREATE INDEX_MAIN_TS "INDEX_MAIN_TS" DATAFILE '/db/knpc/domain/IX_MAIN.DB' 
    SIZE 10485760 AUTOEXTEND ON NEXT 1048576 
    MAXSIZE 10485760000 LOGGING ONLINE PERMANENT BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL
    AUTOALLOCATE DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/db/knpc/domain/IX_MAIN.DB' RESIZE 10485760;
--
-- # KNPC_INDEX_TS
CREATE TABLESPACE "KNPC_INDEX_TS" DATAFILE '/db/knpc/domain/IKNPC1.DB' 
    SIZE 10485760 AUTOEXTEND ON NEXT 1048576 
    MAXSIZE 1048576000 LOGGING ONLINE PERMANENT BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL
    AUTOALLOCATE DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/db/knpc/domain/IKNPC1.DB' RESIZE 10485760;
--
-- # KNPC_TS
CREATE TABLESPACE "KNPC_TS" DATAFILE '/db/knpc/domain/PKNPC1.DB' 
    SIZE 10485760 AUTOEXTEND ON NEXT 1048576 
    MAXSIZE 1048576000 LOGGING ONLINE PERMANENT BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL
    AUTOALLOCATE DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/db/knpc/domain/PKNPC1.DB' RESIZE 10485760;
--
-- # MAIN_TS
CREATE TABLESPACE "MAIN_TS" DATAFILE '/db/knpc/domain/IN_MAIN.DB' 
    SIZE 15728640 AUTOEXTEND ON NEXT 10485760
    MAXSIZE 1048576000 LOGGING ONLINE PERMANENT BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL
    AUTOALLOCATE DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
ALTER DATABASE DATAFILE '/db/knpc/domain/IN_MAIN.DB' RESIZE 10485760;
--
-- # TEMP1_TS
CREATE TEMPORARY TABLESPACE "TEMP1_TS" TEMPFILE '/db/knpc/domain/TEMP1.DB' 
    SIZE 15728640 AUTOEXTEND ON NEXT 1048576 
    MAXSIZE 1048576000 EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10485760;

/* ============================================= 
    Create Oracle project Users & Roles, 
     assign to tablespace
   ============================================= */
-- # INTOOLS_ENGINEER  
CREATE ROLE "INTOOLS_ENGINEER";
--
-- # IN_DBAMN
CREATE USER "IN_DBAMN" IDENTIFIED BY VALUES "IN_DBAMN" DEFAULT
    TABLESPACE "MAIN_TS" TEMPORARY TABLESPACE "TEMP1_TS";
ALTER USER "IN_DBAMN" DEFAULT TABLESPACE "MAIN_TS" 
    TEMPORARY TABLESPACE "TEMP1_TS" ACCOUNT UNLOCK ;
ALTER USER "IN_DBAMN" QUOTA UNLIMITED ON INDEX_MAIN_TS;
ALTER USER "IN_DBAMN" QUOTA UNLIMITED ON MAIN_TS;
--
-- # INTOOLS_LOGIN 
CREATE USER "INTOOLS_LOGIN" IDENTIFIED BY VALUES "INTOOLS_LOGIN" DEFAULT
    TABLESPACE "MAIN_TS" TEMPORARY TABLESPACE "TEMP1_TS";
--
-- # KNPC 
CREATE USER "KNPC" IDENTIFIED BY VALUES "KNPC" DEFAULT
    TABLESPACE "KNPC_TS" TEMPORARY TABLESPACE "TEMP1_TS";
CREATE USER "KNPC_VIEW" IDENTIFIED BY VALUES "KNPC_VIEW" DEFAULT
    TABLESPACE "KNPC_TS" TEMPORARY TABLESPACE "TEMP1_TS";
--
-- # DEFAULT PROFILE  
ALTER PROFILE "DEFAULT" LIMIT COMPOSITE_LIMIT UNLIMITED SESSIONS_PER_USER UNLIMITED CPU_PER_SESSION
UNLIMITED CPU_PER_CALL UNLIMITED LOGICAL_READS_PER_SESSION UNLIMITED LOGICAL_READS_PER_CALL
UNLIMITED IDLE_TIME UNLIMITED CONNECT_TIME UNLIMITED PRIVATE_SGA UNLIMITED FAILED_LOGIN_ATTEMPTS 10
PASSWORD_LIFE_TIME 180 PASSWORD_REUSE_TIME UNLIMITED PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL PASSWORD_LOCK_TIME 1 PASSWORD_GRACE_TIME 7
