/* ============================================= 
    Create TABLESPACE and DATAFILES
   ============================================= */
--
-- # ORADBA_TS  <<tablespace>>
CREATE TABLESPACE "ORADBA_TS" DATAFILE '/db/oradba/ORADBA_TS.DB' 
  SIZE 10485760 AUTOEXTEND ON NEXT 1048576 
  MAXSIZE 1048576000 LOGGING ONLINE PERMANENT BLOCKSIZE 8192 EXTENT MANAGEMENT LOCAL
  AUTOALLOCATE DEFAULT NOCOMPRESS SEGMENT SPACE MANAGEMENT AUTO;
--
-- # ORADBA_TMP_TS  <<tablespace>>
CREATE TEMPORARY TABLESPACE "ORADBA_TMP_TS" TEMPFILE '/db/oradba/ORADBA_TMP.DB'  
  SIZE 15728640 AUTOEXTEND ON NEXT 1048576 
  MAXSIZE 1048576000 EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10485760;

/* ============================================= 
    Create Users and assign tablespace
   ============================================= */
--
-- # ORADBA_TS    <<user>>
CREATE USER "ORADBA" IDENTIFIED BY "ORADBA" DEFAULT
    TABLESPACE "ORADBA_TS" TEMPORARY TABLESPACE "ORADBA_TMP_TS";
    
ALTER USER "ORADBA" QUOTA UNLIMITED ON ORADBA_TS;           --Set tablespace quota
ALTER USER "ORADBA_TS" QUOTA UNLIMITED ON ORADBA_TMP_TS;

GRANT "CONNECT" TO "ORADBA_TS" ;                            --Added tablespace grants
GRANT CREATE SESSION TO "ORADBA_TS" ;
GRANT BACKUP ANY TABLE TO "ORADBA_TS" ;

/* ============================================= 
    Create Users and assign tablespace
   ============================================= */
--
-- # <<synonyms>>
CREATE SYNONYM "ORADBA"."ADD_SPEC1" FOR "KNPC"."ADD_SPEC1"
CREATE SYNONYM "ORADBA"."ADD_SPEC2" FOR "KNPC"."ADD_SPEC2";
CREATE SYNONYM "ORADBA"."ADD_SPEC3" FOR "KNPC"."ADD_SPEC3";
CREATE SYNONYM "ORADBA"."ADD_SPEC4" FOR "KNPC"."ADD_SPEC4";
CREATE SYNONYM "ORADBA"."ADD_SPEC1" FOR "KNPC"."ADD_SPEC1";
CREATE SYNONYM "ORADBA"."ADD_SPEC5" FOR "KNPC"."ADD_SPEC5";
CREATE SYNONYM "ORADBA"."ADD_SPEC6" FOR "KNPC"."ADD_SPEC6";
CREATE SYNONYM "ORADBA"."ADD_SPEC7" FOR "KNPC"."ADD_SPEC7";
CREATE SYNONYM "ORADBA"."ADD_SPEC8" FOR "KNPC"."ADD_SPEC8";
CREATE SYNONYM "ORADBA"."ADD_SPEC9" FOR "KNPC"."ADD_SPEC9";
CREATE SYNONYM "ORADBA"."ANALYZER" FOR "KNPC"."ANALYZER";
CREATE SYNONYM "ORADBA"."AREA_CLASS" FOR "KNPC"."AREA_CLASS";
CREATE SYNONYM "ORADBA"."CHANNEL" FOR "KNPC"."CHANNEL";
CREATE SYNONYM "ORADBA"."CHANNEL_TYPE" FOR "KNPC"."CHANNEL_TYPE";
CREATE SYNONYM "ORADBA"."CMPNT_CRITICALITY" FOR "KNPC"."CMPNT_CRITICALITY";
CREATE SYNONYM "ORADBA"."CMPNT_FUNC_TYPE_DWG_EXT_BLK" FOR "KNPC"."CMPNT_FUNC_TYPE_DWG_EXT_BLK";
CREATE SYNONYM "ORADBA"."COMPONENT" FOR "KNPC"."COMPONENT";
CREATE SYNONYM "ORADBA"."COMPONENT_CATEGORY" FOR "KNPC"."COMPONENT_CATEGORY";
CREATE SYNONYM "ORADBA"."COMPONENT_CATEGORY_COMPONENT" FOR "KNPC"."COMPONENT_CATEGORY_COMPONENT";
CREATE SYNONYM "ORADBA"."COMPONENT_CERTIFICATION" FOR "KNPC"."COMPONENT_CERTIFICATION";
CREATE SYNONYM "ORADBA"."COMPONENT_DIMENSIONAL" FOR "KNPC"."COMPONENT_DIMENSIONAL";
CREATE SYNONYM "ORADBA"."COMPONENT_DISCONNECT_ASSOCIATE" FOR "KNPC"."COMPONENT_DISCONNECT_ASSOCIATE";
CREATE SYNONYM "ORADBA"."COMPONENT_DOCUMENT" FOR "KNPC"."COMPONENT_DOCUMENT";
CREATE SYNONYM "ORADBA"."COMPONENT_DWG_EXTERNAL_BLOCK" FOR "KNPC"."COMPONENT_DWG_EXTERNAL_BLOCK";
CREATE SYNONYM "ORADBA"."COMPONENT_FUNC_SUB_CATEGORY" FOR "KNPC"."COMPONENT_FUNC_SUB_CATEGORY";
CREATE SYNONYM "ORADBA"."COMPONENT_FUNCTION_BLOCK" FOR "KNPC"."COMPONENT_FUNCTION_BLOCK";
CREATE SYNONYM "ORADBA"."COMPONENT_FUNCTION_HU_TYPE" FOR "KNPC"."COMPONENT_FUNCTION_HU_TYPE";
CREATE SYNONYM "ORADBA"."COMPONENT_FUNCTION_PROFILE" FOR "KNPC"."COMPONENT_FUNCTION_PROFILE";
CREATE SYNONYM "ORADBA"."COMPONENT_FUNCTION_TYPE" FOR "KNPC"."COMPONENT_FUNCTION_TYPE";
CREATE SYNONYM "ORADBA"."COMPONENT_HANDLE" FOR "KNPC"."COMPONENT_HANDLE";
CREATE SYNONYM "ORADBA"."COMPONENT_LOCATION" FOR "KNPC"."COMPONENT_LOCATION";
CREATE SYNONYM "ORADBA"."COMPONENT_MFR" FOR "KNPC"."COMPONENT_MFR";
CREATE SYNONYM "ORADBA"."COMPONENT_MOD" FOR "KNPC"."COMPONENT_MOD";
CREATE SYNONYM "ORADBA"."COMPONENT_PROFILE_WIRING" FOR "KNPC"."COMPONENT_PROFILE_WIRING";
CREATE SYNONYM "ORADBA"."COMPONENT_SYS_IO_TYPE" FOR "KNPC"."COMPONENT_SYS_IO_TYPE";
CREATE SYNONYM "ORADBA"."CONTROL_VALVE" FOR "KNPC"."CONTROL_VALVE";
CREATE SYNONYM "ORADBA"."CONTROL_VALVE_BODY_TYPE" FOR "KNPC"."CONTROL_VALVE_BODY_TYPE";
CREATE SYNONYM "ORADBA"."CONTROL_VALVE_CHARACTERISTIC" FOR "KNPC"."CONTROL_VALVE_CHARACTERISTIC";
CREATE SYNONYM "ORADBA"."CONTROL_VALVE_CONFIG" FOR "KNPC"."CONTROL_VALVE_CONFIG";
CREATE SYNONYM "ORADBA"."CONTROL_VALVE_SWAGE" FOR "KNPC"."CONTROL_VALVE_SWAGE";
CREATE SYNONYM "ORADBA"."CONTROL_VALVE_TYPE" FOR "KNPC"."CONTROL_VALVE_TYPE";
CREATE SYNONYM "ORADBA"."CONTROLLER" FOR "KNPC"."CONTROLLER";
CREATE SYNONYM "ORADBA"."CONTROLLER_TYPE" FOR "KNPC"."CONTROLLER_TYPE";
CREATE SYNONYM "ORADBA"."CONVENTION_STRUCTURE" FOR "KNPC"."CONVENTION_STRUCTURE";
CREATE SYNONYM "ORADBA"."CONVENTION_TEMP" FOR "KNPC"."CONVENTION_TEMP";
CREATE SYNONYM "ORADBA"."COPY_INTOOLS_DD" FOR "KNPC"."COPY_INTOOLS_DD";
CREATE SYNONYM "ORADBA"."CORRELATTS" FOR "KNPC"."CORRELATTS";
CREATE SYNONYM "ORADBA"."CROSSTAB" FOR "KNPC"."CROSSTAB";
CREATE SYNONYM "ORADBA"."CURRENT_INFO" FOR "KNPC"."CURRENT_INFO";
CREATE SYNONYM "ORADBA"."CV_CONFIG_COMPONENT_MOD" FOR "KNPC"."CV_CONFIG_COMPONENT_MOD";
CREATE SYNONYM "ORADBA"."DATAWINDOW_RESIZE_SETTINGS" FOR "KNPC"."DATAWINDOW_RESIZE_SETTINGS";
CREATE SYNONYM "ORADBA"."DCS_FUNC_BLOCK_IO_TERM" FOR "KNPC"."DCS_FUNC_BLOCK_IO_TERM";
CREATE SYNONYM "ORADBA"."DCS_FUNC_BLOCK_TYPE" FOR "KNPC"."DCS_FUNC_BLOCK_TYPE";
CREATE SYNONYM "ORADBA"."DCS_VENDOR_DEFINITION" FOR "KNPC"."DCS_VENDOR_DEFINITION";
CREATE SYNONYM "ORADBA"."DEVICE_INSTR_TYPE" FOR "KNPC"."DEVICE_INSTR_TYPE";
CREATE SYNONYM "ORADBA"."DOCUMENT_QUERY" FOR "KNPC"."DOCUMENT_QUERY";
CREATE SYNONYM "ORADBA"."DOCUMENT_REGISTRY" FOR "KNPC"."DOCUMENT_REGISTRY";
CREATE SYNONYM "ORADBA"."DOCUMENT_TYPE" FOR "KNPC"."DOCUMENT_TYPE";
CREATE SYNONYM "ORADBA"."DOCUMENTS" FOR "KNPC"."DOCUMENTS";
CREATE SYNONYM "ORADBA"."DRAWING" FOR "KNPC"."DRAWING";
CREATE SYNONYM "ORADBA"."DRAWING_APPROVAL" FOR "KNPC"."DRAWING_APPROVAL";
CREATE SYNONYM "ORADBA"."DRAWING_EXTERNAL_BLOCK" FOR "KNPC"."DRAWING_EXTERNAL_BLOCK";
CREATE SYNONYM "ORADBA"."DRAWING_EXTERNAL_BLOCK_TYPE" FOR "KNPC"."DRAWING_EXTERNAL_BLOCK_TYPE";
CREATE SYNONYM "ORADBA"."DRAWING_INTERNAL_BLOCK" FOR "KNPC"."DRAWING_INTERNAL_BLOCK";
CREATE SYNONYM "ORADBA"."DRAWING_OBJECT" FOR "KNPC"."DRAWING_OBJECT";
CREATE SYNONYM "ORADBA"."DRAWING_REVISION" FOR "KNPC"."DRAWING_REVISION";
CREATE SYNONYM "ORADBA"."DRAWING_TYPE" FOR "KNPC"."DRAWING_TYPE";
CREATE SYNONYM "ORADBA"."DRAWING_TYPE_COL_DATA" FOR "KNPC"."DRAWING_TYPE_COL_DATA";
CREATE SYNONYM "ORADBA"."DRAWING_TYPE_COLUMNS" FOR "KNPC"."DRAWING_TYPE_COLUMNS";
CREATE SYNONYM "ORADBA"."ENGINEER_PROJECT_PRIVILEGY" FOR "KNPC"."ENGINEER_PROJECT_PRIVILEGY";
CREATE SYNONYM "ORADBA"."ENGINEERING_PROJECT" FOR "KNPC"."ENGINEERING_PROJECT";
CREATE SYNONYM "ORADBA"."ENGINEERING_PROJECT_LOGO" FOR "KNPC"."ENGINEERING_PROJECT_LOGO";
CREATE SYNONYM "ORADBA"."ENGINEERING_SCOPE_LEVEL" FOR "KNPC"."ENGINEERING_SCOPE_LEVEL";
CREATE SYNONYM "ORADBA"."ENTITIES" FOR "KNPC"."ENTITIES";
CREATE SYNONYM "ORADBA"."ENTITY_TYPE" FOR "KNPC"."ENTITY_TYPE";
CREATE SYNONYM "ORADBA"."ENUMERATIONS" FOR "KNPC"."ENUMERATIONS";
CREATE SYNONYM "ORADBA"."EQUIPMENT" FOR "KNPC"."EQUIPMENT";
CREATE SYNONYM "ORADBA"."EQUIPMENT_TYPE" FOR "KNPC"."EQUIPMENT_TYPE";
CREATE SYNONYM "ORADBA"."FIELDBUS_SPUR_LENGTH" FOR "KNPC"."FIELDBUS_SPUR_LENGTH";
CREATE SYNONYM "ORADBA"."FILTER_SORT_CONDITION" FOR "KNPC"."FILTER_SORT_CONDITION";
CREATE SYNONYM "ORADBA"."FILTEREDRELATIONSHIP" FOR "KNPC"."FILTEREDRELATIONSHIP";
CREATE SYNONYM "ORADBA"."FLOW" FOR "KNPC"."FLOW";
CREATE SYNONYM "ORADBA"."FLOW_METER_SUBTYPE" FOR "KNPC"."FLOW_METER_SUBTYPE";
CREATE SYNONYM "ORADBA"."FLOW_METER_TYPE" FOR "KNPC"."FLOW_METER_TYPE";
CREATE SYNONYM "ORADBA"."FLUID_PROPERTY" FOR "KNPC"."FLUID_PROPERTY";
CREATE SYNONYM "ORADBA"."FREQUENCY" FOR "KNPC"."FREQUENCY";
CREATE SYNONYM "ORADBA"."FUNCTION_BLOCK_MFR_FUNC_REV" FOR "KNPC"."FUNCTION_BLOCK_MFR_FUNC_REV";
CREATE SYNONYM "ORADBA"."FUNCTION_BLOCK_TYPE" FOR "KNPC"."FUNCTION_BLOCK_TYPE";
CREATE SYNONYM "ORADBA"."FUNCTION_SUPERPOSITION" FOR "KNPC"."FUNCTION_SUPERPOSITION";
CREATE SYNONYM "ORADBA"."GENERAL_SIGNAL" FOR "KNPC"."GENERAL_SIGNAL";
CREATE SYNONYM "ORADBA"."GENERIC_TERMINOLOGY" FOR "KNPC"."GENERIC_TERMINOLOGY";
CREATE SYNONYM "ORADBA"."HARDWARE_POSITION" FOR "KNPC"."HARDWARE_POSITION";
CREATE SYNONYM "ORADBA"."HART_SIGNAL" FOR "KNPC"."HART_SIGNAL";
CREATE SYNONYM "ORADBA"."HONEYWELL_VALUES" FOR "KNPC"."HONEYWELL_VALUES";
CREATE SYNONYM "ORADBA"."HOOK_UP" FOR "KNPC"."HOOK_UP";
CREATE SYNONYM "ORADBA"."HOOK_UP_COMPONENT" FOR "KNPC"."HOOK_UP_COMPONENT";
CREATE SYNONYM "ORADBA"."HOOK_UP_DRAWING" FOR "KNPC"."HOOK_UP_DRAWING";
CREATE SYNONYM "ORADBA"."HOOK_UP_DRAWING_SETTINGS" FOR "KNPC"."HOOK_UP_DRAWING_SETTINGS";
CREATE SYNONYM "ORADBA"."HOOK_UP_ITEM_FILTER" FOR "KNPC"."HOOK_UP_ITEM_FILTER";
CREATE SYNONYM "ORADBA"."HOOK_UP_ITEM_LIBRARY" FOR "KNPC"."HOOK_UP_ITEM_LIBRARY";
CREATE SYNONYM "ORADBA"."HOOK_UP_ITEM_LIST" FOR "KNPC"."HOOK_UP_ITEM_LIST";
CREATE SYNONYM "ORADBA"."HOOK_UP_LIB_HIST" FOR "KNPC"."HOOK_UP_LIB_HIST";
CREATE SYNONYM "ORADBA"."HOOK_UP_PLANT_SUB_LIB" FOR "KNPC"."HOOK_UP_PLANT_SUB_LIB";
CREATE SYNONYM "ORADBA"."HOOK_UP_SUB_LIBRARIES" FOR "KNPC"."HOOK_UP_SUB_LIBRARIES";
CREATE SYNONYM "ORADBA"."HOOK_UP_TYPE" FOR "KNPC"."HOOK_UP_TYPE";
CREATE SYNONYM "ORADBA"."INTRINSIC_SAFE_CABLE_TYPE" FOR "KNPC"."INTRINSIC_SAFE_CABLE_TYPE";
CREATE SYNONYM "ORADBA"."INTRINSIC_SAFE_CALC_TYPICAL" FOR "KNPC"."INTRINSIC_SAFE_CALC_TYPICAL";
CREATE SYNONYM "ORADBA"."INTRINSIC_SAFE_PANEL_MFR" FOR "KNPC"."INTRINSIC_SAFE_PANEL_MFR";
CREATE SYNONYM "ORADBA"."INTRINSIC_SAFE_PANEL_MFR_MOD" FOR "KNPC"."INTRINSIC_SAFE_PANEL_MFR_MOD";
CREATE SYNONYM "ORADBA"."INTRINSIC_SAFE_PANEL_TYPE" FOR "KNPC"."INTRINSIC_SAFE_PANEL_TYPE";
CREATE SYNONYM "ORADBA"."ITEM" FOR "KNPC"."ITEM";
CREATE SYNONYM "ORADBA"."ITEM_LIST" FOR "KNPC"."ITEM_LIST";
CREATE SYNONYM "ORADBA"."ITEM_LIST_MFR" FOR "KNPC"."ITEM_LIST_MFR";
CREATE SYNONYM "ORADBA"."ITEM_RELATIONS" FOR "KNPC"."ITEM_RELATIONS";
CREATE SYNONYM "ORADBA"."ITEMATTRIBUTIONS" FOR "KNPC"."ITEMATTRIBUTIONS";
CREATE SYNONYM "ORADBA"."LEVEL_INSTRUMENT" FOR "KNPC"."LEVEL_INSTRUMENT";
CREATE SYNONYM "ORADBA"."LINE" FOR "KNPC"."LINE";
CREATE SYNONYM "ORADBA"."LINE_COMPONENT" FOR "KNPC"."LINE_COMPONENT";
CREATE SYNONYM "ORADBA"."LINE_COPY_FIELDS" FOR "KNPC"."LINE_COPY_FIELDS";
CREATE SYNONYM "ORADBA"."LINE_DD_PIPE_SCHEDULE" FOR "KNPC"."LINE_DD_PIPE_SCHEDULE";
CREATE SYNONYM "ORADBA"."LINE_DD_WALL_THICKNESS" FOR "KNPC"."LINE_DD_WALL_THICKNESS";
CREATE SYNONYM "ORADBA"."LINE_TYPE" FOR "KNPC"."LINE_TYPE";
CREATE SYNONYM "ORADBA"."LINEAR_TYPE" FOR "KNPC"."LINEAR_TYPE";
CREATE SYNONYM "ORADBA"."LINK" FOR "KNPC"."LINK";
CREATE SYNONYM "ORADBA"."LINK_GROUP" FOR "KNPC"."LINK_GROUP";
CREATE SYNONYM "ORADBA"."LINK_STORE" FOR "KNPC"."LINK_STORE";
CREATE SYNONYM "ORADBA"."LOOP" FOR "KNPC"."LOOP";
CREATE SYNONYM "ORADBA"."LOOP_DRAWING" FOR "KNPC"."LOOP_DRAWING";
CREATE SYNONYM "ORADBA"."LOOP_FUNCTION" FOR "KNPC"."LOOP_FUNCTION";
CREATE SYNONYM "ORADBA"."LOOP_GENERATION_METHOD" FOR "KNPC"."LOOP_GENERATION_METHOD";
CREATE SYNONYM "ORADBA"."LOOP_PROC" FOR "KNPC"."LOOP_PROC";
CREATE SYNONYM "ORADBA"."LOOP_TYPE" FOR "KNPC"."LOOP_TYPE";
CREATE SYNONYM "ORADBA"."MEASURING_COMPONENT" FOR "KNPC"."MEASURING_COMPONENT";
CREATE SYNONYM "ORADBA"."MFR_DIMENSIONAL" FOR "KNPC"."MFR_DIMENSIONAL";
CREATE SYNONYM "ORADBA"."NUMBER_OF_PHASES" FOR "KNPC"."NUMBER_OF_PHASES";
CREATE SYNONYM "ORADBA"."OBJECT_DEF" FOR "KNPC"."OBJECT_DEF";
CREATE SYNONYM "ORADBA"."OBJECT_DEF_INTERFACE_DEF" FOR "KNPC"."OBJECT_DEF_INTERFACE_DEF";
CREATE SYNONYM "ORADBA"."OBJECT_INTERFACE_COLUMNS" FOR "KNPC"."OBJECT_INTERFACE_COLUMNS";
CREATE SYNONYM "ORADBA"."OBJECT_INTERFACE_DEF" FOR "KNPC"."OBJECT_INTERFACE_DEF";
CREATE SYNONYM "ORADBA"."OBJECT_PROP_ENUM_DEF" FOR "KNPC"."OBJECT_PROP_ENUM_DEF";
CREATE SYNONYM "ORADBA"."OBJECT_REGISTRY" FOR "KNPC"."OBJECT_REGISTRY";
CREATE SYNONYM "ORADBA"."OBJECT_REL" FOR "KNPC"."OBJECT_REL";
CREATE SYNONYM "ORADBA"."OBJECT_REL_DEF" FOR "KNPC"."OBJECT_REL_DEF";
CREATE SYNONYM "ORADBA"."OBJECT_REL_DEF_DOCUMENT_TYPE" FOR "KNPC"."OBJECT_REL_DEF_DOCUMENT_TYPE";
CREATE SYNONYM "ORADBA"."OBJECT_REMOTE_UID_LIST" FOR "KNPC"."OBJECT_REMOTE_UID_LIST";
CREATE SYNONYM "ORADBA"."OBJECT_SCHEMA" FOR "KNPC"."OBJECT_SCHEMA";
CREATE SYNONYM "ORADBA"."OBJECT_SCHEMA_VIEW" FOR "KNPC"."OBJECT_SCHEMA_VIEW";
CREATE SYNONYM "ORADBA"."OWNER" FOR "KNPC"."OWNER";
CREATE SYNONYM "ORADBA"."PD_FIELD_PROPERTY" FOR "KNPC"."PD_FIELD_PROPERTY";
CREATE SYNONYM "ORADBA"."PD_GENERAL" FOR "KNPC"."PD_GENERAL";
CREATE SYNONYM "ORADBA"."PD_INSULATION" FOR "KNPC"."PD_INSULATION";
CREATE SYNONYM "ORADBA"."PD_NOT_ASSIGN" FOR "KNPC"."PD_NOT_ASSIGN";
CREATE SYNONYM "ORADBA"."PIPE_CLASS" FOR "KNPC"."PIPE_CLASS";
CREATE SYNONYM "ORADBA"."PIPE_MATERIAL" FOR "KNPC"."PIPE_MATERIAL";
CREATE SYNONYM "ORADBA"."PIPE_STANDARD" FOR "KNPC"."PIPE_STANDARD";
CREATE SYNONYM "ORADBA"."PIPING_PORT" FOR "KNPC"."PIPING_PORT";
CREATE SYNONYM "ORADBA"."PLANT" FOR "KNPC"."PLANT";
CREATE SYNONYM "ORADBA"."PLANT_AREA" FOR "KNPC"."PLANT_AREA";
CREATE SYNONYM "ORADBA"."PLANT_AREA_UNIT" FOR "KNPC"."PLANT_AREA_UNIT";
CREATE SYNONYM "ORADBA"."PLANT_HU_TYPE_PIPE_CLASS" FOR "KNPC"."PLANT_HU_TYPE_PIPE_CLASS";
CREATE SYNONYM "ORADBA"."PLANT_STRUCTURE_HIERARCHY" FOR "KNPC"."PLANT_STRUCTURE_HIERARCHY";
CREATE SYNONYM "ORADBA"."PM_TASK" FOR "KNPC"."PM_TASK";
CREATE SYNONYM "ORADBA"."PORT" FOR "KNPC"."PORT";
CREATE SYNONYM "ORADBA"."PRESSURE" FOR "KNPC"."PRESSURE";
CREATE SYNONYM "ORADBA"."PROCESS_CONDITION" FOR "KNPC"."PROCESS_CONDITION";
CREATE SYNONYM "ORADBA"."PROCESS_CONNECTION_CLASS" FOR "KNPC"."PROCESS_CONNECTION_CLASS";
CREATE SYNONYM "ORADBA"."PROCESS_CONNECTION_END_PREP" FOR "KNPC"."PROCESS_CONNECTION_END_PREP";
CREATE SYNONYM "ORADBA"."PROCESS_FUNCTION" FOR "KNPC"."PROCESS_FUNCTION";
CREATE SYNONYM "ORADBA"."PROCESS_FUNCTION_LINK" FOR "KNPC"."PROCESS_FUNCTION_LINK";
CREATE SYNONYM "ORADBA"."PROJECT_GROUP" FOR "KNPC"."PROJECT_GROUP";
CREATE SYNONYM "ORADBA"."PROJECT_INFO" FOR "KNPC"."PROJECT_INFO";
CREATE SYNONYM "ORADBA"."PROJECT_PREFERENCES" FOR "KNPC"."PROJECT_PREFERENCES";
CREATE SYNONYM "ORADBA"."PROJECT_USER" FOR "KNPC"."PROJECT_USER";
CREATE SYNONYM "ORADBA"."RELATIONSHIPS" FOR "KNPC"."RELATIONSHIPS";
CREATE SYNONYM "ORADBA"."RELIEF_VALVE" FOR "KNPC"."RELIEF_VALVE";
CREATE SYNONYM "ORADBA"."RELIEF_VALVE_CONFIG" FOR "KNPC"."RELIEF_VALVE_CONFIG";
CREATE SYNONYM "ORADBA"."RESERVED_NEXT_ID" FOR "KNPC"."RESERVED_NEXT_ID";
CREATE SYNONYM "ORADBA"."REVISION" FOR "KNPC"."REVISION";
CREATE SYNONYM "ORADBA"."REVISION_STYLE" FOR "KNPC"."REVISION_STYLE";
CREATE SYNONYM "ORADBA"."REVISION_STYLE_SYNTAX" FOR "KNPC"."REVISION_STYLE_SYNTAX";
CREATE SYNONYM "ORADBA"."REVISION_STYLE_TYPE" FOR "KNPC"."REVISION_STYLE_TYPE";
CREATE SYNONYM "ORADBA"."REVISION_TITLE" FOR "KNPC"."REVISION_TITLE";
CREATE SYNONYM "ORADBA"."RULE_DETAIL" FOR "KNPC"."RULE_DETAIL";
CREATE SYNONYM "ORADBA"."RULE_DETAILS" FOR "KNPC"."RULE_DETAILS";
CREATE SYNONYM "ORADBA"."RULE_GENERAL" FOR "KNPC"."RULE_GENERAL";
CREATE SYNONYM "ORADBA"."RULE_GROUP" FOR "KNPC"."RULE_GROUP";
CREATE SYNONYM "ORADBA"."RULE_HEADER" FOR "KNPC"."RULE_HEADER";
CREATE SYNONYM "ORADBA"."SEQ_OR_NEXT_ID" FOR "KNPC"."SEQ_OR_NEXT_ID";
CREATE SYNONYM "ORADBA"."SEQ_SPEC_REVISION" FOR "KNPC"."SEQ_SPEC_REVISION";
CREATE SYNONYM "ORADBA"."SOURCEDESTOBJECTRELS" FOR "KNPC"."SOURCEDESTOBJECTRELS";
CREATE SYNONYM "ORADBA"."SPEC_ATTRIBUTE" FOR "KNPC"."SPEC_ATTRIBUTE";
CREATE SYNONYM "ORADBA"."SPEC_BROWSE_ATTRIBUTE_LIST" FOR "KNPC"."SPEC_BROWSE_ATTRIBUTE_LIST";
CREATE SYNONYM "ORADBA"."SPEC_BROWSE_FORM_LIST" FOR "KNPC"."SPEC_BROWSE_FORM_LIST";
CREATE SYNONYM "ORADBA"."SPEC_BROWSE_LIST" FOR "KNPC"."SPEC_BROWSE_LIST";
CREATE SYNONYM "ORADBA"."SPEC_DEFAULT" FOR "KNPC"."SPEC_DEFAULT";
CREATE SYNONYM "ORADBA"."SPEC_DEFAULT_IMAGE" FOR "KNPC"."SPEC_DEFAULT_IMAGE";
CREATE SYNONYM "ORADBA"."SPEC_ENTITY" FOR "KNPC"."SPEC_ENTITY";
CREATE SYNONYM "ORADBA"."SPEC_FIELD_MAP" FOR "KNPC"."SPEC_FIELD_MAP";
CREATE SYNONYM "ORADBA"."SPEC_FORM" FOR "KNPC"."SPEC_FORM";
CREATE SYNONYM "ORADBA"."SPEC_FORM_ATTRIBUTE_LIST" FOR "KNPC"."SPEC_FORM_ATTRIBUTE_LIST";
CREATE SYNONYM "ORADBA"."SPEC_FORM_ATTRIBUTE_SELECTION" FOR "KNPC"."SPEC_FORM_ATTRIBUTE_SELECTION";
CREATE SYNONYM "ORADBA"."SPEC_FORM_MAPPING" FOR "KNPC"."SPEC_FORM_MAPPING";
CREATE SYNONYM "ORADBA"."SPEC_FORM_NOTE" FOR "KNPC"."SPEC_FORM_NOTE";
CREATE SYNONYM "ORADBA"."SPEC_FORM_NOTE_BODY" FOR "KNPC"."SPEC_FORM_NOTE_BODY";
CREATE SYNONYM "ORADBA"."SPEC_FORM_PAGES" FOR "KNPC"."SPEC_FORM_PAGES";
CREATE SYNONYM "ORADBA"."SPEC_FORM_PSR" FOR "KNPC"."SPEC_FORM_PSR";
CREATE SYNONYM "ORADBA"."SPEC_FORMAT" FOR "KNPC"."SPEC_FORMAT";
CREATE SYNONYM "ORADBA"."SPEC_FORMAT_ATTRIBUTES" FOR "KNPC"."SPEC_FORMAT_ATTRIBUTES";
CREATE SYNONYM "ORADBA"."SPEC_FORMAT_LAYOUT" FOR "KNPC"."SPEC_FORMAT_LAYOUT";
CREATE SYNONYM "ORADBA"."SPEC_FORMAT_SYNTAX" FOR "KNPC"."SPEC_FORMAT_SYNTAX";
CREATE SYNONYM "ORADBA"."SPEC_PAGE_SECTION" FOR "KNPC"."SPEC_PAGE_SECTION";
CREATE SYNONYM "ORADBA"."SPEC_PAGES" FOR "KNPC"."SPEC_PAGES";
CREATE SYNONYM "ORADBA"."SPEC_REVISION_DOCUMENT_MULTI" FOR "KNPC"."SPEC_REVISION_DOCUMENT_MULTI";
CREATE SYNONYM "ORADBA"."SPEC_REVISION_STORE" FOR "KNPC"."SPEC_REVISION_STORE";
CREATE SYNONYM "ORADBA"."SPEC_SECTION" FOR "KNPC"."SPEC_SECTION";
CREATE SYNONYM "ORADBA"."SPEC_SHEET_DATA" FOR "KNPC"."SPEC_SHEET_DATA";
CREATE SYNONYM "ORADBA"."SPEC_SHEET_DATA_FORM_DWG" FOR "KNPC"."SPEC_SHEET_DATA_FORM_DWG";
CREATE SYNONYM "ORADBA"."SPEC_TABLE_LIST" FOR "KNPC"."SPEC_TABLE_LIST";
CREATE SYNONYM "ORADBA"."TABLE_LIST" FOR "KNPC"."TABLE_LIST";
CREATE SYNONYM "ORADBA"."TABLES_COPY" FOR "KNPC"."TABLES_COPY";
CREATE SYNONYM "ORADBA"."TAG_CATEGORY" FOR "KNPC"."TAG_CATEGORY";
CREATE SYNONYM "ORADBA"."TAG_CONVENTION_ATTRIBUTES" FOR "KNPC"."TAG_CONVENTION_ATTRIBUTES";
CREATE SYNONYM "ORADBA"."TAG_CONVENTION_STRUCTURE" FOR "KNPC"."TAG_CONVENTION_STRUCTURE";
CREATE SYNONYM "ORADBA"."TAG_CONVENTION_TYPE" FOR "KNPC"."TAG_CONVENTION_TYPE";
CREATE SYNONYM "ORADBA"."TARGET_VERSION" FOR "KNPC"."TARGET_VERSION";
CREATE SYNONYM "ORADBA"."TASK_PROPERTIES" FOR "KNPC"."TASK_PROPERTIES";
CREATE SYNONYM "ORADBA"."TASK_STATUS" FOR "KNPC"."TASK_STATUS";
CREATE SYNONYM "ORADBA"."TASK_TYPE" FOR "KNPC"."TASK_TYPE";
CREATE SYNONYM "ORADBA"."TASKS" FOR "KNPC"."TASKS";
CREATE SYNONYM "ORADBA"."TEMPERATURE" FOR "KNPC"."TEMPERATURE";
CREATE SYNONYM "ORADBA"."UDF_COMPONENT" FOR "KNPC"."UDF_COMPONENT";
CREATE SYNONYM "ORADBA"."UDF_COMPONENT_ATTRIBUTES" FOR "KNPC"."UDF_COMPONENT_ATTRIBUTES";
CREATE SYNONYM "ORADBA"."UDF_CS_TAG" FOR "KNPC"."UDF_CS_TAG";
CREATE SYNONYM "ORADBA"."UDF_DRAWING" FOR "KNPC"."UDF_DRAWING";
CREATE SYNONYM "ORADBA"."UDF_EQUIPMENT" FOR "KNPC"."UDF_EQUIPMENT";
CREATE SYNONYM "ORADBA"."UDF_FUNCTION" FOR "KNPC"."UDF_FUNCTION";
CREATE SYNONYM "ORADBA"."UDF_HEADER" FOR "KNPC"."UDF_HEADER";
CREATE SYNONYM "ORADBA"."UDF_LINE" FOR "KNPC"."UDF_LINE";
CREATE SYNONYM "ORADBA"."UDF_LOOP" FOR "KNPC"."UDF_LOOP";
CREATE SYNONYM "ORADBA"."UDT_PROFILE" FOR "KNPC"."UDT_PROFILE";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT1" FOR "KNPC"."UDT_SUPPORT1";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT10" FOR "KNPC"."UDT_SUPPORT10";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT11" FOR "KNPC"."UDT_SUPPORT11";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT12" FOR "KNPC"."UDT_SUPPORT12";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT13" FOR "KNPC"."UDT_SUPPORT13";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT14" FOR "KNPC"."UDT_SUPPORT14";""
CREATE SYNONYM "ORADBA"."UDT_SUPPORT15" FOR "KNPC"."UDT_SUPPORT15";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT16" FOR "KNPC"."UDT_SUPPORT16";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT2" FOR "KNPC"."UDT_SUPPORT2";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT3" FOR "KNPC"."UDT_SUPPORT3";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT4" FOR "KNPC"."UDT_SUPPORT4";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT5" FOR "KNPC"."UDT_SUPPORT5";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT6" FOR "KNPC"."UDT_SUPPORT6";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT7" FOR "KNPC"."UDT_SUPPORT7";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT8" FOR "KNPC"."UDT_SUPPORT8";
CREATE SYNONYM "ORADBA"."UDT_SUPPORT9" FOR "KNPC"."UDT_SUPPORT9";
CREATE SYNONYM "ORADBA"."UNIQUEATTS" FOR "KNPC"."UNIQUEATTS";
CREATE SYNONYM "ORADBA"."UNIT_OF_MEASURE" FOR "KNPC"."UNIT_OF_MEASURE";
CREATE SYNONYM "ORADBA"."UNIT_OF_MEASURE_TYPE" FOR "KNPC"."UNIT_OF_MEASURE_TYPE";
CREATE SYNONYM "ORADBA"."UNIT_TAG_CONVENTION" FOR "KNPC"."UNIT_TAG_CONVENTION";
CREATE SYNONYM "ORADBA"."UNLOAD_LIST" FOR "KNPC"."UNLOAD_LIST";
CREATE SYNONYM "ORADBA"."USER_GROUP" FOR "KNPC"."USER_GROUP";
CREATE SYNONYM "ORADBA"."VIEW_BROWSE" FOR "KNPC"."VIEW_BROWSE";
CREATE SYNONYM "ORADBA"."WIDE_PARAMETERS" FOR "KNPC"."WIDE_PARAMETERS";
CREATE SYNONYM "ORADBA"."WORK_ACTIVITY" FOR "KNPC"."WORK_ACTIVITY";
CREATE SYNONYM "ORADBA"."WORK_REQUEST_REASON" FOR "KNPC"."WORK_REQUEST_REASON";
CREATE SYNONYM "ORADBA"."SPEC_FORM_COL_MATRIX" FOR "KNPC"."SPEC_FORM_COL_MATRIX";
CREATE SYNONYM "ORADBA"."BROWSE_VIEW" FOR "KNPC"."BROWSE_VIEW";
CREATE SYNONYM "ORADBA"."SPEC_COLUMNS" FOR "KNPC"."SPEC_COLUMNS";



/* 
    ////////////////////////////////////////////////////////////////////////////////////
    // @plsql
    //
    //  Code: ODBA_Create_BaseSchema.sql
    //  Desc: Create the main schema to be used for the base toolkit. This is designed
    //         to be created in the same instance as the project db instance. As this
    //         schema is not registered with SPI this schema is only managed or handled
    //         by external source.
    //
    //  Author: JayLotz
    //    Date: 20-Sep-2015
    ////////////////////////////////////////////////////////////////////////JayLotz///// 
*/
