/* =============================== 
    Create Oracle project Users & Roles
   =============================== */
--
-- # INTOOLS_ENGINEER  
CREATE ROLE "INTOOLS_ENGINEER";
--
-- # IN_DBAMN
CREATE USER "IN_DBAMN" IDENTIFIED BY VALUES "IN_DBAMN" DEFAULT
    TABLESPACE "MAIN_TS" TEMPORARY TABLESPACE "TEMP1_TS";
ALTER USER "IN_DBAMN" DEFAULT TABLESPACE "MAIN_TS" 
    TEMPORARY TABLESPACE "TEMP1_TS" ACCOUNT UNLOCK ;
ALTER USER "IN_DBAMN" QUOTA UNLIMITED ON INDEX_MAIN_TS;
ALTER USER "IN_DBAMN" QUOTA UNLIMITED ON MAIN_TS;
--
-- # INTOOLS_LOGIN 
CREATE USER "INTOOLS_LOGIN" IDENTIFIED BY VALUES "INTOOLS_LOGIN" DEFAULT
    TABLESPACE "MAIN_TS" TEMPORARY TABLESPACE "TEMP1_TS";
--
-- # KNPC 
CREATE USER "KNPC" IDENTIFIED BY VALUES "KNPC" DEFAULT
    TABLESPACE "KNPC_TS" TEMPORARY TABLESPACE "TEMP1_TS";
CREATE USER "KNPC_VIEW" IDENTIFIED BY VALUES "KNPC_VIEW" DEFAULT
    TABLESPACE "KNPC_TS" TEMPORARY TABLESPACE "TEMP1_TS";
--
-- # ORADBA  
CREATE USER "ORADBA" IDENTIFIED BY VALUES "ORADBA" DEFAULT
    TABLESPACE "DBA_MAIN_TS" TEMPORARY TABLESPACE "TEMP";
--
-- # DEFAULT PROFILE  
ALTER PROFILE "DEFAULT" LIMIT COMPOSITE_LIMIT UNLIMITED SESSIONS_PER_USER UNLIMITED CPU_PER_SESSION
UNLIMITED CPU_PER_CALL UNLIMITED LOGICAL_READS_PER_SESSION UNLIMITED LOGICAL_READS_PER_CALL
UNLIMITED IDLE_TIME UNLIMITED CONNECT_TIME UNLIMITED PRIVATE_SGA UNLIMITED FAILED_LOGIN_ATTEMPTS 10
PASSWORD_LIFE_TIME 180 PASSWORD_REUSE_TIME UNLIMITED PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL PASSWORD_LOCK_TIME 1 PASSWORD_GRACE_TIME 7
