CREATE SMALLFILE TABLESPACE ORADBA_TS 
    DATAFILE 
        '/db/oradba/ORADBA__TS' SIZE 10485760 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    NOLOGGING 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
